application: you-move
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /map
  script: main.py
  
- url: /map/(.*)
  script: main.py

- url: /
  script: index.py

- url: /(.*)
  static_files: site/\1
  upload: site/(.*)

